### ISSUE TITLE
Are overlapping segments considered as non-intersecting?

### ISSUE THREAD

**Issue by lycantropos** [ivvaan/balaban-segments-intersections#1]
I've tried the following snippet
```cpp
    TLineSegment1 segment;
    segment.org = TPlaneVect{0, 0};
    segment.shift = TPlaneVect{1, 1};
    TLineSegment1 segs[] = {segment, segment};
    auto seg_type = line1;
    int4 alg = optimal;
    int4 n = 2;

    SimpleCounter reg;
    reg.counter = 0;
    CLine1SegmentCollection<SimpleCounter> coll;
    coll.Init(n, segs);
    coll.SetRegistrator(&reg);

    COptimalIntFinder fi;
    fi.prepare_ends(&coll);
    fi.find_intersections(&coll);
```
and `reg.counter` is `0`, which is odd, I've expected it to be `2`. Am I missing something or algorithms don't handle overlapping segments?

**Comment by lycantropos** [comment]
Also what about multiple intersections? Only the first one gets registered? Because
```cpp
TLineSegment1 from_endpoints(REAL start_x, REAL start_y, REAL end_x, REAL end_y) {
    TLineSegment1 result;
    result.org = TPlaneVect{start_x, start_y};
    result.shift = TPlaneVect{end_x - start_x, end_y - start_y};
    return result;
}
...
TLineSegment1 segs[] = {from_endpoints(0, 0, 1, 1), from_endpoints(0, 1, 1, 0), from_endpoints(0.5, 0, 0.5, 1)};
```
with other as above gets me `1` instead of `2`.

**Comment by ivvaan** [comment]
1. Yes, overlapping segments are considered as parallel and non-intersecting. The implementation assumes segments are in common position. Overlapping segments is degenerate case. For degenerate cases the implementations of segments' collections classes (CLine1SegmentCollection, CLine2SegmentCollection, CArcSegmentCollection) may not work at all and needs to be rewritten. Besides, for degenerate cases desired result is ambiguous and must be defined on application basis. 
2. Line segments are assumed  intersecting maximal in one point. Arc segments are assumed capable to intersect each other in one or two points. Once again, only non-degenerate cases are processed correctly.
3. Some kind of degenerate cases are processed in new CGraphSegmentCollection. It has been created to find intersections of a graph edges. In this situation we definitely has a degenerate situation at the graph vertices. At each of the vertices several edges "intersects". But normaly we don't need those trivial "interesections" so CGraphSegmentCollection class correctly process the situation and doesn't count them.
